SELECT (AVG(?pm25Instance) AS ?pm_25) ?sensor ?placeName WHERE {

    ?pm25obs a sosa:Observation .	
    ?pm25obs sosa:observedProperty saqi:ParticulateMatter2_5Concentration .
    ?pm25obs sosa:hasResult ?pm25Instance .
  	?pm25obs sosa:resultTime ?time .
    ?pm25obs saqi:atPlace ?place .
    ?pm25obs saqi:madeBySensor ?sensor .
    
    ?place saqi:hasName ?placeName .
  } 
  GROUP BY ?sensor ?placeName
  LIMIT 10000

JOIN

    SELECT ?pm25Instance ?pm10Instance ?place ?time WHERE {

    ?pm25obs a sosa:Observation ;
    sosa:observedProperty saqi:ParticulateMatter2_5Concentration ;
    sosa:hasResult ?pm25Instance ;
  	sosa:resultTime ?time ;
    saqi:atPlace ?place .

    ?pm10obs a sosa:Observation ;
    sosa:observedProperty saqi:ParticulateMatter10Concentration ;
    sosa:hasResult ?pm10Instance ;
  	sosa:resultTime ?time ;
    saqi:atPlace ?place .
  
  } 
  LIMIT 30

SELECT ?pm25Instance ?pm10Instance ?time ?place ?sensor WHERE {

?obs1 a sosa:Observation .
?obs1 sosa:resultTime ?time .
?obs1 saqi:atPlace ?place .
?obs1 saqi:madeBySensor ?sensor .
      
?obs2 a sosa:Observation .
?obs2 sosa:resultTime ?time .
?obs2 saqi:atPlace ?place .
?obs2 saqi:madeBySensor ?sensor .
  
?obs1 sosa:observedProperty saqi:ParticulateMatter2_5Concentration .
?obs1 sosa:hasResult ?pm25Instance .
?obs2 sosa:observedProperty saqi:ParticulateMatter10Concentration .
?obs2 sosa:hasResult ?pm10Instance .
  
}
LIMIT 10000


SELECT (AVG(?pm10Instance) AS ?pm_10) (AVG(?pm25Instance) AS ?pm_25) ?sensor WHERE {

?obs1 a sosa:Observation .
?obs1 sosa:resultTime ?time .
?obs1 saqi:atPlace ?place .
?obs1 saqi:madeBySensor ?sensor .
      
?obs2 a sosa:Observation .
?obs2 sosa:resultTime ?time .
?obs2 saqi:atPlace ?place .
?obs2 saqi:madeBySensor ?sensor .
  
?obs1 sosa:observedProperty saqi:ParticulateMatter2_5Concentration .
?obs1 sosa:hasResult ?pm25Instance .
?obs2 sosa:observedProperty saqi:ParticulateMatter10Concentration .
?obs2 sosa:hasResult ?pm10Instance .
  
 FILTER (
    ?place=saqi:ShaheenBagh &&
    ?time > "2021-11-01T00:00:00+05:30"^^xsd:dateTime &&
    ?time < "2021-11-05T00:00:00+05:30"^^xsd:dateTime
  )
    
}
GROUP BY ?sensor
LIMIT 10000

